version: 0.0
os: linux
files:
  - source: build/
    destination: /var/www/html
hooks:
  BeforeInstall:
    - location: scripts/npm_install.sh
      runas: root
      timeout: 300
  ApplicationStart:
    - location: scripts/npm_start.sh
      runas: root
      timeout: 300